/*
 *   This file will be regenerated by `mulle-sourcetree-to-c` via
 *   `mulle-sde reflect` and any edits will be lost.
 *   Suppress generation of this file with:
 *
 *      mulle-sde environment set MULLE_SOURCETREE_TO_C_IMPORT_FILE DISABLE
 *
 *   To not let mulle-sourcetree-to-c generate any header files:
 *
 *      mulle-sde environment set MULLE_SOURCETREE_TO_C_RUN DISABLE
 *
 */

// You can tweak the following #import with these commands.
// (Use DF3C3483-2013-4497-9F14-B0C1CE88B422 instead of MulleCivetWeb if there are duplicate entries)
//    remove:             `mulle-sourcetree mark MulleCivetWeb no-header`
//    rename:             `mulle-sde dependency|library set MulleCivetWeb include whatever.h`
//    reorder:            `mulle-sourcetree move MulleCivetWeb <up|down>`
//    toggle #import:     `mulle-sourcetree mark MulleCivetWeb [no-]import`
//    toggle public:      `mulle-sourcetree mark MulleCivetWeb [no-]public`
//    toggle optional:    `mulle-sourcetree mark MulleCivetWeb [no-]require`
//    remove for platform:`mulle-sourcetree mark MulleCivetWeb no-platform-<uname>`
//        (use mulle-sourcetree-to-c --unames for known values)
#import <MulleCivetWeb/MulleCivetWeb.h>   // MulleCivetWeb

// You can tweak the following #import with these commands.
// (Use 3A3D12D2-F255-487F-8FC2-896F476B750D instead of MulleObjCJSMNFoundation if there are duplicate entries)
//    remove:             `mulle-sourcetree mark MulleObjCJSMNFoundation no-header`
//    rename:             `mulle-sde dependency|library set MulleObjCJSMNFoundation include whatever.h`
//    reorder:            `mulle-sourcetree move MulleObjCJSMNFoundation <up|down>`
//    toggle #import:     `mulle-sourcetree mark MulleObjCJSMNFoundation [no-]import`
//    toggle public:      `mulle-sourcetree mark MulleObjCJSMNFoundation [no-]public`
//    toggle optional:    `mulle-sourcetree mark MulleObjCJSMNFoundation [no-]require`
//    remove for platform:`mulle-sourcetree mark MulleObjCJSMNFoundation no-platform-<uname>`
//        (use mulle-sourcetree-to-c --unames for known values)
#import <MulleObjCJSMNFoundation/MulleObjCJSMNFoundation.h>   // MulleObjCJSMNFoundation

#ifdef __has_include
# if __has_include( "_MulleWebServer-include.h")
#  include "_MulleWebServer-include.h"
# endif
#endif

