/*
 *   This file will be regenerated by `mulle-project-versioncheck`.
 *   Any edits will be lost.
 */
#if defined( MULLE_CIVET_WEB_VERSION)
# if MULLE_CIVET_WEB_VERSION < ((0 << 20) | (17 << 8) | 6)
#  error "MulleCivetWeb is too old"
# endif
# if MULLE_CIVET_WEB_VERSION >= ((0 << 20) | (18 << 8) | 0)
#  error "MulleCivetWeb is too new"
# endif
#endif

#if defined( MULLE_FOUNDATION_VERSION)
# if MULLE_FOUNDATION_VERSION < ((0 << 20) | (20 << 8) | 0)
#  error "MulleFoundation is too old"
# endif
# if MULLE_FOUNDATION_VERSION >= ((0 << 20) | (21 << 8) | 0)
#  error "MulleFoundation is too new"
# endif
#endif

#if defined( MULLE_OBJC_JSMN_FOUNDATION_VERSION)
# if MULLE_OBJC_JSMN_FOUNDATION_VERSION < ((0 << 20) | (18 << 8) | 2)
#  error "MulleObjCJSMNFoundation is too old"
# endif
# if MULLE_OBJC_JSMN_FOUNDATION_VERSION >= ((0 << 20) | (19 << 8) | 0)
#  error "MulleObjCJSMNFoundation is too new"
# endif
#endif
