      { @selector( MulleObjCDeps), @selector( MulleCivetWeb) },      // 3c20656f;MulleObjCDeps;ba3d249e;MulleCivetWeb
      { @selector( MulleObjCDeps), @selector( MulleObjCJSMNFoundation) },      // 3c20656f;MulleObjCDeps;383fe71a;MulleObjCJSMNFoundation
      { @selector( MulleCivetWebServer), @selector( OS) },      // 7d0338e7;MulleCivetWebServer;de4ab977;OS
      { @selector( MulleWebHandlerManager), MULLE_OBJC_NO_CATEGORYID },      // 25021a34;MulleWebHandlerManager;;
      { @selector( NSObject), @selector( MulleWebHandler) },      // b3a66256;NSObject;c10de1ca;MulleWebHandler
