      { @selector( MulleObjCDeps), @selector( MulleCivetWeb) },      // 3c20656f;MulleObjCDeps;ba3d249e;MulleCivetWeb
      { @selector( MulleObjCDeps), @selector( MulleFoundation) },      // 3c20656f;MulleObjCDeps;46ed3b36;MulleFoundation
      { @selector( MulleObjCDeps), @selector( MulleFoundationBase) },      // 3c20656f;MulleObjCDeps;efab19ea;MulleFoundationBase
      { @selector( MulleObjCDeps), @selector( MulleObjCCalendarFoundation) },      // 3c20656f;MulleObjCDeps;6b608d36;MulleObjCCalendarFoundation
      { @selector( MulleObjCDeps), @selector( MulleObjCDecimalFoundation) },      // 3c20656f;MulleObjCDeps;f04a7a28;MulleObjCDecimalFoundation
      { @selector( MulleObjCDeps), @selector( MulleObjCHTTPFoundation) },      // 3c20656f;MulleObjCDeps;457d3115;MulleObjCHTTPFoundation
      { @selector( MulleObjCDeps), @selector( MulleObjCInetFoundation) },      // 3c20656f;MulleObjCDeps;088ec1b3;MulleObjCInetFoundation
      { @selector( MulleObjCDeps), @selector( MulleObjCJSMNFoundation) },      // 3c20656f;MulleObjCDeps;383fe71a;MulleObjCJSMNFoundation
      { @selector( MulleObjCDeps), @selector( MulleObjCOSFoundation) },      // 3c20656f;MulleObjCDeps;94ffe970;MulleObjCOSFoundation
      { @selector( MulleCivetWebServer), @selector( OS) },      // 7d0338e7;MulleCivetWebServer;de4ab977;OS
      { @selector( MulleWebHandlerManager), MULLE_OBJC_NO_CATEGORYID },      // 25021a34;MulleWebHandlerManager;;
      { @selector( NSObject), @selector( MulleWebHandler) },      // b3a66256;NSObject;c10de1ca;MulleWebHandler
