/*
*   This file will be regenerated by `mulle-sde update` and any edits will be
*   lost. Suppress generation of this file with:
*      mulle-sde environment --global \
*         set MULLE_SOURCETREE_TO_C_IMPORT_FILE DISABLE
*
*   To not generate any header files:
*      mulle-sde environment --global \
*         set MULLE_SOURCETREE_TO_C_RUN DISABLE
*/

#ifndef _mulle_web_import_h__
#define _mulle_web_import_h__

// How to tweak the following MulleFoundation #import
//    remove:          `mulle-sourcetree mark MulleFoundation no-header`
//    rename:          `mulle-sourcetree mark MulleFoundation set include whatever.h`
//    toggle public:   `mulle-sourcetree mark MulleFoundation [no-]public`
//    toggle optional: `mulle-sourcetree mark MulleFoundation [no-]require`
//    remove for os:   `mulle-sourcetree mark MulleFoundation no-os-<osname>`
# import <MulleFoundation/MulleFoundation.h>   // MulleFoundation

// How to tweak the following MulleCurl #import
//    remove:          `mulle-sourcetree mark MulleCurl no-header`
//    rename:          `mulle-sourcetree mark MulleCurl set include whatever.h`
//    toggle public:   `mulle-sourcetree mark MulleCurl [no-]public`
//    toggle optional: `mulle-sourcetree mark MulleCurl [no-]require`
//    remove for os:   `mulle-sourcetree mark MulleCurl no-os-<osname>`
# ifdef __has_include
#  if __has_include(<MulleCurl/MulleCurl.h>)
#   import <MulleCurl/MulleCurl.h>   // MulleCurl
#   define HAVE_LIB_MULLE_CURL
#  endif
# endif

// How to tweak the following MulleCivetWeb #import
//    remove:          `mulle-sourcetree mark MulleCivetWeb no-header`
//    rename:          `mulle-sourcetree mark MulleCivetWeb set include whatever.h`
//    toggle public:   `mulle-sourcetree mark MulleCivetWeb [no-]public`
//    toggle optional: `mulle-sourcetree mark MulleCivetWeb [no-]require`
//    remove for os:   `mulle-sourcetree mark MulleCivetWeb no-os-<osname>`
# ifdef __has_include
#  if __has_include(<MulleCivetWeb/MulleCivetWeb.h>)
#   import <MulleCivetWeb/MulleCivetWeb.h>   // MulleCivetWeb
#   define HAVE_LIB_MULLE_CIVET_WEB
#  endif
# endif

#include "_MulleWeb-include.h"


#endif
