      { @selector( MulleObjCLoader), @selector( MulleCivetWeb) },      // 47a9beb6;MulleObjCLoader;ba3d249e;MulleCivetWeb
      { @selector( MulleObjCLoader), @selector( MulleCurl) },      // 47a9beb6;MulleObjCLoader;9714448a;MulleCurl
      { @selector( MulleObjCLoader), @selector( MulleFoundation) },      // 47a9beb6;MulleObjCLoader;46ed3b36;MulleFoundation
      { @selector( MulleCurl), @selector( NSURL) },      // 9714448a;MulleCurl;6b1e8f73;NSURL
      { @selector( MulleJSMNParser), @selector( MulleCurlParser) },      // 11d4e75e;MulleJSMNParser;3ef706fe;MulleCurlParser
