#
# cmake/_Headers.cmake is generated by `mulle-sde`. Edits will be lost.
#
if( MULLE_TRACE_INCLUDE)
   MESSAGE( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

set( INCLUDE_DIRS
src
)

set( PRIVATE_HEADERS
src/import-private.h
)

set( PUBLIC_HEADERS
src/MulleCivetWebServer+OS.h
src/MulleObjCLoader+MulleWebServer.h
src/MulleWebHandler.h
src/MulleWebServer.h
src/import.h
)

