#
# cmake/_Sources.cmake is generated by `mulle-sde`. Edits will be lost.
#
if( MULLE_TRACE_INCLUDE)
   MESSAGE( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

set( SOURCES
src/MulleCurl+NSURL.m
src/MulleJSMNParser+MulleCurlParser.m
src/MulleWeb.m
src/MulleWeb-shlib.c
)

set( STAGE2_SOURCES
src/MulleObjCLoader+MulleWeb.m
)
